### PR TITLE
Filesize simplification

### PR DESCRIPTION
**Pull request by bbolli**
Changes proposed in this pull request:

* better test coverage filesize.py
* code simplification

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks for the PR!

Do you know why the type checking fails?

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

src/humanize/filesize.py:80: error: Returning Any from function declared to return "str"  [no-any-return]
Found 1 error in 1 file (checked 11 source files)
```

**Comment by bbolli** [comment]
> Do you know why the type checking fails?

Not really... My local mypy installation (v0.991) does not report any type violations in `src/humanize`.

**Comment by hugovk** [comment]
Hmm, the same version is used by the CI:

https://github.com/python-humanize/humanize/blob/60e3b4785d78d03c5cf23d20c9fc3323a6882dfc/.pre-commit-config.yaml#L61-L66

Also with the `--strict` option.

**Comment by hugovk** [comment]
Updated to make mypy happy.

The more type-safe way is:

```python
ret = format % (base * bytes_ / unit) + s
assert isinstance(ret, str)
return ret
```

But this shorter version is good enough for here. Thanks @AlexWaygood for the tips!

**Comment by hugovk** [comment]
> * better test coverage filesize.py

Well, 100% to 100% is no change, and ironically by reducing the total covered lines, it's slightly decreased the total coverage percentage 🙃 

> * code simplification

but this is appreciated :)

Thank you!

**Pull request merged**
