### PR TITLE
Add Italian translation for "thousand" and fix singulars

### PR DESCRIPTION
**Pull request by aborruso**
I have added the thousand Italian string

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks! Are there different forms for singular and plural? If so, please put the singular first and plural second.

**Comment by aborruso** [comment]
> Thanks! Are there different forms for singular and plural? If so, please put the singular first and plural second.

I have seen that there are several errors on singulars. I correct them all

**Comment by aborruso** [comment]
> Thanks! Are there different forms for singular and plural? If so, please put the singular first and plural second.

Done, thank you

https://github.com/python-humanize/humanize/pull/97/commits/31b9ead104f4bea30f344970ec3010e783d54e75

**Comment by hugovk** [comment]
Grazie mille!

**Comment by aborruso** [comment]
> Grazie mille!

how to use humanize and these two PR of mines? Do you will create a new release or do I must install if from git?

Thank you

**Comment by hugovk** [comment]
I've just released them in 4.6.0. Thanks again!

**Comment by aborruso** [comment]
> I've just released them in 4.6.0. Thanks again!

thank you

**Pull request merged**
