### PR TITLE
Replace setuptools with hatchling

### PR DESCRIPTION
**Pull request by hugovk**
Changes proposed in this pull request:

* Replace setuptools with hatchling
* Replace setuptools_scm with hatch-vcs
* Include translation `.mo` files as artifacts
* Delete `setup.py` (`setup.cfg` was deleted in #90)

### CODE REVIEW

**Comment by hugovk** [comment]
The coverage drop indicates translations aren't tested.

These files are not in Git and are generated by `scripts/generate-translation-binaries.sh` at release time:

```
./src/humanize/locale/ar/LC_MESSAGES/humanize.mo
./src/humanize/locale/bn_BD/LC_MESSAGES/humanize.mo
./src/humanize/locale/ca_ES/LC_MESSAGES/humanize.mo
./src/humanize/locale/da_DK/LC_MESSAGES/humanize.mo
./src/humanize/locale/de_DE/LC_MESSAGES/humanize.mo
./src/humanize/locale/el_GR/LC_MESSAGES/humanize.mo
./src/humanize/locale/es_ES/LC_MESSAGES/humanize.mo
./src/humanize/locale/fa_IR/LC_MESSAGES/humanize.mo
./src/humanize/locale/fi_FI/LC_MESSAGES/humanize.mo
./src/humanize/locale/fr_FR/LC_MESSAGES/humanize.mo
./src/humanize/locale/id_ID/LC_MESSAGES/humanize.mo
./src/humanize/locale/it_IT/LC_MESSAGES/humanize.mo
./src/humanize/locale/ja_JP/LC_MESSAGES/humanize.mo
./src/humanize/locale/ko_KR/LC_MESSAGES/humanize.mo
./src/humanize/locale/nl_NL/LC_MESSAGES/humanize.mo
./src/humanize/locale/pl_PL/LC_MESSAGES/humanize.mo
./src/humanize/locale/pt_BR/LC_MESSAGES/humanize.mo
./src/humanize/locale/pt_PT/LC_MESSAGES/humanize.mo
./src/humanize/locale/ru_RU/LC_MESSAGES/humanize.mo
./src/humanize/locale/sk_SK/LC_MESSAGES/humanize.mo
./src/humanize/locale/sl_SI/LC_MESSAGES/humanize.mo
./src/humanize/locale/sv_SE/LC_MESSAGES/humanize.mo
./src/humanize/locale/tr_TR/LC_MESSAGES/humanize.mo
./src/humanize/locale/uk_UA/LC_MESSAGES/humanize.mo
./src/humanize/locale/vi_VN/LC_MESSAGES/humanize.mo
./src/humanize/locale/zh_CN/LC_MESSAGES/humanize.mo
./src/humanize/locale/zh_HK/LC_MESSAGES/humanize.mo
```

With setuptools they're included in the distribution files by `MANIFEST.in`:

```in
recursive-include src/humanize/locale *.mo
```

But Hatchling doesn't use `MANIFEST.in` and they're missing.

We probably need something like [this](https://github.com/hugovk/em-keyboard/blob/84c70075f963148d523085da47f340c059a9b568/pyproject.toml#L67-L68) in `pyproject.toml`:

```toml
[tool.hatch.build.force-include]
"em/emojis.json" = "em/emojis.json"
```

But I'd like to avoid listing all the files manually, so we don't need to add new ones when a new translation is added.

**Comment by carterbox** [comment]
What's the motivation for switching to hatch from setuptools?

> But I'd like to avoid listing all the files manually, so we don't need to add new ones when a new translation is added.


Looks like [hatch supports pattern matching](https://hatch.pypa.io/latest/config/build/#patterns). And probably include (not force-include) is sufficient because these files are inside the module.

**Comment by hugovk** [comment]
> What's the motivation for switching to hatch from setuptools?

Well first of all, I'd like to move away from setuptools which is getting a bit old (or ["`setuptools` is a _hot mess_ of legacy code"](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) :). It is being modernised, but there may be some disruption in the process (e.g. https://github.com/pypa/setuptools/issues/3532).

Hatchling is standards compliant, and specifically built based on the new packaging standards for build backends ([PEP 517](https://peps.python.org/pep-0517/)/[PEP 660](https://peps.python.org/pep-0660/)) and the format for metadata declaration ([PEP 621](https://peps.python.org/pep-0621/)/[PEP 631](https://peps.python.org/pep-0631/)).

And I've seen a lot of interest and other projects moving over, here's a few: https://hatch.pypa.io/latest/users/ (It's also the default option in this PyPA tutorial https://packaging.python.org/en/latest/tutorials/packaging-projects/.)

---

> Looks like [hatch supports pattern matching](https://hatch.pypa.io/latest/config/build/#patterns). And probably include (not force-include) is sufficient because these files are inside the module.

Thanks, I'll have a look. Possibly also as [artifacts](https://hatch.pypa.io/latest/config/build/#artifacts).

**Comment by hugovk** [comment]
Updated to include translations as artifacts:

```toml
[tool.hatch.build]
artifacts = [
  "*.mo",
]
```

https://hatch.pypa.io/latest/config/build/#artifacts

---

Note: this was accidentally already included in https://github.com/python-humanize/humanize/pull/90 (and had no effect there), and so not shown in this PR's diff:

```toml
[tool.hatch]
version.source = "vcs"
```

**Comment by hugovk** [comment]
Will release with https://github.com/python-humanize/humanize/pull/90 first, then merge this and it can go in the next release.

**Pull request merged**
