### PR TITLE
Add humanize.metric() for converting big/small numbers to SI units

### PR DESCRIPTION
**Pull request by bwoodsend**
Fixes nothing!

Changes proposed in this pull request:

* Fix scientific() on small positive numbers.
* Add humanize.metric() for converting big/small numbers to SI units.

### CODE REVIEW

**Comment by bwoodsend** [comment]
Uhm, why did precommit do that?

**Comment by hugovk** [comment]
Haha! That's autoflake fixing:

```
src/humanize/__init__.py:5:1: F401 'humanize.number.metric' imported but unused
```

The real fix is to add `metric` to `__all__` in `src/humanize/__init__.py`.

**Comment by hugovk** [comment]
Thanks for this!

For `metric` let's add the required space between the number and the unit (maybe with exceptions for plane angular degrees, minutes, and seconds (°, ′, and ″)?).

https://en.wikipedia.org/wiki/International_System_of_Units#General_rules

I guess we should do this also when there's no SI unit but we end up with a metric `k` or so on?

I think this will replace PR https://github.com/python-humanize/humanize/pull/1 as well.

**Comment by hugovk** [comment]
Thank you!

**Pull request merged**
