### PR TITLE
`metric`: Fix precision format

### PR DESCRIPTION
**Pull request by e-nikolov**
Currently if I try to print a 2 digit number with precision 0, I get this error:
`ValueError: Format specifier missing precision` because the format results in a negative precision number.

This PR makes sure that the precision is at least 0

### CODE REVIEW

**Comment by hugovk** [comment]
Please can you share a snippet of code that reproduces the problem, and also include tests?

**Comment by hugovk** [comment]
Thank you!

**Comment by moi90** [comment]
I ran into the same problem (and found the same fix). It would be great to release a new version to PyPI that includes this fix.

**Comment by hugovk** [comment]
Thanks for the ping, we're long overdue a release, I'll make one this week.

**Comment by hugovk** [comment]
4.10.0 is released!

**Comment by moi90** [comment]
Great!

**Pull request merged**
